_wandb:
    value:
        cli_version: 0.19.10
        m: []
        python_version: 3.9.18
        t:
            "1":
                - 1
                - 5
                - 53
                - 55
            "2":
                - 1
                - 5
                - 53
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.9.18
            "5": 0.19.10
            "8":
                - 5
            "12": 0.19.10
            "13": linux-x86_64
batch_size:
    value: 8
db_folder:
    value: /home/ibroto/Documents/SMC/SPIS/BodyInTransit/DATASET/train
epochs:
    value: 10
learning_rate:
    value: 0.0005
resume:
    value: null
save_every:
    value: 10
window_length:
    value: 125
